//! Piece-square tables.
//!
//! `psq_score(piece, square)` returns a packed middlegame/endgame `Score`
//! covering both material value and positional preference for the given
//! piece being on that square. Two positions with identical piece
//! placement have the same sum of psq scores — which is the starting
//! point of classical evaluation, and the only component that updates
//! incrementally at O(1) per move.
//!
//! Weights are factual numerical data carried over from the Stockfish 11
//! reference (`reference/Stockfish-sf_11/src/psqt.cpp`). Structure here is
//! freshly authored in Rust:
//!
//! - The per-piece positional tables in the reference are asymmetric by
//!   piece (non-pawns are defined only for files a–d and mirrored, pawns
//!   are asymmetric across the whole board). We unfold everything at
//!   compile time into the flat `PSQ[Piece::index()][Square::index()]`.
//! - Black's entries are white's entries, vertically flipped and negated.
//!   The unfold is done once in a `const fn` builder so there's no init()
//!   to call.

use crate::types::{Piece, PieceType, Score, Square, Value};

// =========================================================================
// Half-board piece-square bonuses (files a..d, mirrored for e..h)
// =========================================================================
//
// Each entry is a `Score` pair (middlegame, endgame). Indexed
// `[rank][half_file]` where half_file folds files a..h onto a..d:
// file_a -> 0, ..., file_d -> 3, file_e -> 3, file_h -> 0.
//
// Rank 0 is white's 1st rank (own king's home); rank 7 is white's 8th.
// Black's tables are generated by vertical flip + sign inversion.

const KNIGHT_BONUS: [[Score; 4]; 8] = [
    [
        Score::new(-175, -96),
        Score::new(-92, -65),
        Score::new(-74, -49),
        Score::new(-73, -21),
    ],
    [
        Score::new(-77, -67),
        Score::new(-41, -54),
        Score::new(-27, -18),
        Score::new(-15, 8),
    ],
    [
        Score::new(-61, -40),
        Score::new(-17, -27),
        Score::new(6, -8),
        Score::new(12, 29),
    ],
    [
        Score::new(-35, -35),
        Score::new(8, -2),
        Score::new(40, 13),
        Score::new(49, 28),
    ],
    [
        Score::new(-34, -45),
        Score::new(13, -16),
        Score::new(44, 9),
        Score::new(51, 39),
    ],
    [
        Score::new(-9, -51),
        Score::new(22, -44),
        Score::new(58, -16),
        Score::new(53, 17),
    ],
    [
        Score::new(-67, -69),
        Score::new(-27, -50),
        Score::new(4, -51),
        Score::new(37, 12),
    ],
    [
        Score::new(-201, -100),
        Score::new(-83, -88),
        Score::new(-56, -56),
        Score::new(-26, -17),
    ],
];

const BISHOP_BONUS: [[Score; 4]; 8] = [
    [
        Score::new(-53, -57),
        Score::new(-5, -30),
        Score::new(-8, -37),
        Score::new(-23, -12),
    ],
    [
        Score::new(-15, -37),
        Score::new(8, -13),
        Score::new(19, -17),
        Score::new(4, 1),
    ],
    [
        Score::new(-7, -16),
        Score::new(21, -1),
        Score::new(-5, -2),
        Score::new(17, 10),
    ],
    [
        Score::new(-5, -20),
        Score::new(11, -6),
        Score::new(25, 0),
        Score::new(39, 17),
    ],
    [
        Score::new(-12, -17),
        Score::new(29, -1),
        Score::new(22, -14),
        Score::new(31, 15),
    ],
    [
        Score::new(-16, -30),
        Score::new(6, 6),
        Score::new(1, 4),
        Score::new(11, 6),
    ],
    [
        Score::new(-17, -31),
        Score::new(-14, -20),
        Score::new(5, -1),
        Score::new(0, 1),
    ],
    [
        Score::new(-48, -46),
        Score::new(1, -42),
        Score::new(-14, -37),
        Score::new(-23, -24),
    ],
];

const ROOK_BONUS: [[Score; 4]; 8] = [
    [
        Score::new(-31, -9),
        Score::new(-20, -13),
        Score::new(-14, -10),
        Score::new(-5, -9),
    ],
    [
        Score::new(-21, -12),
        Score::new(-13, -9),
        Score::new(-8, -1),
        Score::new(6, -2),
    ],
    [
        Score::new(-25, 6),
        Score::new(-11, -8),
        Score::new(-1, -2),
        Score::new(3, -6),
    ],
    [
        Score::new(-13, -6),
        Score::new(-5, 1),
        Score::new(-4, -9),
        Score::new(-6, 7),
    ],
    [
        Score::new(-27, -5),
        Score::new(-15, 8),
        Score::new(-4, 7),
        Score::new(3, -6),
    ],
    [
        Score::new(-22, 6),
        Score::new(-2, 1),
        Score::new(6, -7),
        Score::new(12, 10),
    ],
    [
        Score::new(-2, 4),
        Score::new(12, 5),
        Score::new(16, 20),
        Score::new(18, -5),
    ],
    [
        Score::new(-17, 18),
        Score::new(-19, 0),
        Score::new(-1, 19),
        Score::new(9, 13),
    ],
];

const QUEEN_BONUS: [[Score; 4]; 8] = [
    [
        Score::new(3, -69),
        Score::new(-5, -57),
        Score::new(-5, -47),
        Score::new(4, -26),
    ],
    [
        Score::new(-3, -55),
        Score::new(5, -31),
        Score::new(8, -22),
        Score::new(12, -4),
    ],
    [
        Score::new(-3, -39),
        Score::new(6, -18),
        Score::new(13, -9),
        Score::new(7, 3),
    ],
    [
        Score::new(4, -23),
        Score::new(5, -3),
        Score::new(9, 13),
        Score::new(8, 24),
    ],
    [
        Score::new(0, -29),
        Score::new(14, -6),
        Score::new(12, 9),
        Score::new(5, 21),
    ],
    [
        Score::new(-4, -38),
        Score::new(10, -18),
        Score::new(6, -12),
        Score::new(8, 1),
    ],
    [
        Score::new(-5, -50),
        Score::new(6, -27),
        Score::new(10, -24),
        Score::new(8, -8),
    ],
    [
        Score::new(-2, -75),
        Score::new(-2, -52),
        Score::new(1, -43),
        Score::new(-2, -36),
    ],
];

const KING_BONUS: [[Score; 4]; 8] = [
    [
        Score::new(271, 1),
        Score::new(327, 45),
        Score::new(271, 85),
        Score::new(198, 76),
    ],
    [
        Score::new(278, 53),
        Score::new(303, 100),
        Score::new(234, 133),
        Score::new(179, 135),
    ],
    [
        Score::new(195, 88),
        Score::new(258, 130),
        Score::new(169, 169),
        Score::new(120, 175),
    ],
    [
        Score::new(164, 103),
        Score::new(190, 156),
        Score::new(138, 172),
        Score::new(98, 172),
    ],
    [
        Score::new(154, 96),
        Score::new(179, 166),
        Score::new(105, 199),
        Score::new(70, 199),
    ],
    [
        Score::new(123, 92),
        Score::new(145, 172),
        Score::new(81, 184),
        Score::new(31, 191),
    ],
    [
        Score::new(88, 47),
        Score::new(120, 121),
        Score::new(65, 116),
        Score::new(33, 131),
    ],
    [
        Score::new(59, 11),
        Score::new(89, 59),
        Score::new(45, 73),
        Score::new(-1, 78),
    ],
];

// =========================================================================
// Pawn table (asymmetric across all eight files)
// =========================================================================
//
// Ranks 0 and 7 are unused: a white pawn on rank 1 shouldn't exist, and
// a pawn reaching rank 8 promotes into something else before being
// scored. They're left zero. Ranks 1 through 6 are populated from the
// reference.

const PAWN_BONUS: [[Score; 8]; 8] = [
    // Rank 1 (unused for pawns)
    [Score::ZERO; 8],
    // Rank 2
    [
        Score::new(3, -10),
        Score::new(3, -6),
        Score::new(10, 10),
        Score::new(19, 0),
        Score::new(16, 14),
        Score::new(19, 7),
        Score::new(7, -5),
        Score::new(-5, -19),
    ],
    // Rank 3
    [
        Score::new(-9, -10),
        Score::new(-15, -10),
        Score::new(11, -10),
        Score::new(15, 4),
        Score::new(32, 4),
        Score::new(22, 3),
        Score::new(5, -6),
        Score::new(-22, -4),
    ],
    // Rank 4
    [
        Score::new(-8, 6),
        Score::new(-23, -2),
        Score::new(6, -8),
        Score::new(20, -4),
        Score::new(40, -13),
        Score::new(17, -12),
        Score::new(4, -10),
        Score::new(-12, -9),
    ],
    // Rank 5
    [
        Score::new(13, 9),
        Score::new(0, 4),
        Score::new(-13, 3),
        Score::new(1, -12),
        Score::new(11, -12),
        Score::new(-2, -6),
        Score::new(-13, 13),
        Score::new(5, 8),
    ],
    // Rank 6
    [
        Score::new(-5, 28),
        Score::new(-12, 20),
        Score::new(-7, 21),
        Score::new(22, 28),
        Score::new(-8, 30),
        Score::new(-5, 7),
        Score::new(-15, 6),
        Score::new(-18, 13),
    ],
    // Rank 7
    [
        Score::new(-7, 0),
        Score::new(7, -11),
        Score::new(-3, 12),
        Score::new(-13, 21),
        Score::new(5, 25),
        Score::new(-16, 19),
        Score::new(10, 4),
        Score::new(-8, 7),
    ],
    // Rank 8 (unused for pawns — they've promoted)
    [Score::ZERO; 8],
];

// =========================================================================
// Fully-expanded table: PSQ[Piece::index()][Square::index()]
// =========================================================================
//
// Each entry combines:
//   - The piece's material value (from `types::Value`), as a Score.
//   - The piece's positional bonus for that square.
//
// White entries are built by indexing the half-board tables with
// (rank, file-folded-to-queenside). Black entries are the white entries
// vertically flipped and sign-inverted, matching how the reference
// post-processes `psq[~pc][~s] = -psq[pc][s]`.

/// Material value of a piece type, as a `Score` (material is the same in
/// both game phases *except* for the precomputed MG/EG piece values).
const fn material_score(pt: PieceType) -> Score {
    match pt {
        PieceType::Pawn => Score::new(Value::PAWN_MG.0, Value::PAWN_EG.0),
        PieceType::Knight => Score::new(Value::KNIGHT_MG.0, Value::KNIGHT_EG.0),
        PieceType::Bishop => Score::new(Value::BISHOP_MG.0, Value::BISHOP_EG.0),
        PieceType::Rook => Score::new(Value::ROOK_MG.0, Value::ROOK_EG.0),
        PieceType::Queen => Score::new(Value::QUEEN_MG.0, Value::QUEEN_EG.0),
        PieceType::King => Score::ZERO, // Kings have no material value in psqt scoring.
    }
}

/// Positional bonus for a white piece of the given type, at the given
/// (rank, file). For all types except pawns the table is file-symmetric,
/// so we fold file into a half-file index first.
const fn white_positional_bonus(pt: PieceType, rank: usize, file: usize) -> Score {
    let half_file = if file < 4 { file } else { 7 - file };
    match pt {
        PieceType::Pawn => PAWN_BONUS[rank][file],
        PieceType::Knight => KNIGHT_BONUS[rank][half_file],
        PieceType::Bishop => BISHOP_BONUS[rank][half_file],
        PieceType::Rook => ROOK_BONUS[rank][half_file],
        PieceType::Queen => QUEEN_BONUS[rank][half_file],
        PieceType::King => KING_BONUS[rank][half_file],
    }
}

const fn build_psq() -> [[Score; 64]; 15] {
    let mut table = [[Score::ZERO; 64]; 15];

    let piece_types: [PieceType; 6] = [
        PieceType::Pawn,
        PieceType::Knight,
        PieceType::Bishop,
        PieceType::Rook,
        PieceType::Queen,
        PieceType::King,
    ];

    let mut i = 0;
    while i < 6 {
        let pt = piece_types[i];
        let material = material_score(pt);

        // Piece indices for white and black versions of `pt`.
        // White pawns = 1, knights = 2, ..., kings = 6.
        // Black pawns = 9, knights = 10, ..., kings = 14.
        let white_index = pt as usize;
        let black_index = (pt as usize) | 8;

        let mut sq_idx = 0usize;
        while sq_idx < 64 {
            let file = sq_idx & 7;
            let rank = sq_idx >> 3;

            // White's score: material + positional from the perspective of
            // (rank, file).
            let bonus = white_positional_bonus(pt, rank, file);
            let white_score = Score(material.0 + bonus.0);
            table[white_index][sq_idx] = white_score;

            // Black's score: same piece on the vertically-flipped square,
            // with both mg and eg sign-inverted. (Vertical flip matches
            // how the reference defines `~s`.)
            let flipped_sq_idx = sq_idx ^ 56;
            table[black_index][flipped_sq_idx] = Score(-white_score.0);

            sq_idx += 1;
        }
        i += 1;
    }

    table
}

/// `PSQ[piece.index()][square.index()]` is the material + positional score
/// of a piece of that kind and color sitting on that square, from white's
/// point of view (so black's contributions are already negative).
pub static PSQ: [[Score; 64]; 15] = build_psq();

// =========================================================================
// Lookup
// =========================================================================

/// Score of this piece being on this square, combining material value and
/// positional preference. White contributes a positive score; black
/// contributes a negative score.
pub fn psq_score(piece: Piece, square: Square) -> Score {
    PSQ[piece.index()][square.index()]
}

// =========================================================================
// Tests
// =========================================================================

#[cfg(test)]
#[path = "psqt_tests.rs"]
mod tests;
